name: aliexpress-dev
channels:
  - defaults
  - conda-forge
dependencies:
  # - python=3.13
  - ipykernel=6.19
  - pandas=2.2.3
  - pip=23.0.1
  - openpyxl=3.1.5
  - jinja2=3.1.2 # necessary for df.style
  - matplotlib=3.10.0 # necessary for df.style
  - highs=1.10.0
  - networkx=3.5
  - plotly=6.1.2
  - pip:
    - pulp==3.1.1
    - flask==3.1.0
    - dotenv==0.9.9
    - -e .[dev]
    - nbformat==5.10.4
