import pandas as pd
import numpy as np
from aliexpress.main import distribute_students_once


def test_distribute_students_once_happy_flow_full():

    result = distribute_students_once(
        path_preferences="tests/integration/voorkeuren.xlsx",
        path_groups_to="tests/integration/groepen.xlsx",
        path_not_together="tests/integration/niet_samen.xlsx",
        on_update=lambda msg: None,
    )

    assert isinstance(result, dict)
    assert "download" in result
    pd.read_excel(
        result["download"]
    )  # Ensure the download can be read as an Excel file

    assert "dataframes" in result
    dfs = result["dataframes"]
    assert isinstance(dfs, dict)
    expected_keys = {
        "Groepsindeling",
        "Klassenoverzicht",
        "Overgangsmatrix",
        "Leerlingtevredenheid",
        "VervuldeWensen",
    }
    assert expected_keys.issubset(dfs.keys())
    # Assert content of the DataFrames
    groepsindeling = dfs["Groepsindeling"]
    assert isinstance(groepsindeling, pd.DataFrame)
    df_expected_groepsindeling = get_expected_groepsindeling()
    pd.testing.assert_frame_equal(groepsindeling, df_expected_groepsindeling)

    klassenoverzicht = dfs["Klassenoverzicht"]
    assert isinstance(klassenoverzicht, pd.DataFrame)
    df_expected_klassenoverzicht = get_expected_klassenoverzicht()
    pd.testing.assert_frame_equal(klassenoverzicht, df_expected_klassenoverzicht)

    overgangsmatrix = dfs["Overgangsmatrix"]
    assert isinstance(overgangsmatrix, pd.DataFrame)
    df_expected_overgangsmatrix = get_expected_overgangsmatrix()
    pd.testing.assert_frame_equal(overgangsmatrix, df_expected_overgangsmatrix)

    leerlingtevredenheid = dfs["Leerlingtevredenheid"]
    assert isinstance(leerlingtevredenheid, pd.io.formats.style.Styler)
    df_expected_leerlingtevredenheid = get_expected_leerlingtevredenheid()
    pd.testing.assert_frame_equal(
        leerlingtevredenheid.data, df_expected_leerlingtevredenheid
    )

    vervuldewensen = dfs["VervuldeWensen"]
    assert isinstance(vervuldewensen, pd.io.formats.style.Styler)
    df_expected_vervuldewensen = get_expected_vervuldewensen()
    pd.testing.assert_frame_equal(vervuldewensen.data, df_expected_vervuldewensen)


def get_expected_groepsindeling():
    expected_groepsindeling = {
        ("Blauw", "Jongen"): {
            1: "Adam (Kab)",
            2: "Lucas (Kab)",
            3: "Benjamin (Tor)",
            4: "Mats (Tor)",
            5: "Julian (Tov)",
            6: "",
            7: "",
            "#": 5,
            "Groepsgrootte": 30,
        },
        ("Blauw", "Meisje"): {
            1: "AnneClaire (Kab)",
            2: "Lois (Kab)",
            3: "Naomi (Kab)",
            4: "Anne (Tov)",
            5: "Esmee (Tov)",
            6: "",
            7: "",
            "#": 5,
            "Groepsgrootte": np.nan,
        },
        ("Geel", "Jongen"): {
            1: "Daan (Tov)",
            2: "Jack (Tov)",
            3: "Lars (Vli)",
            4: "Sven (Vli)",
            5: "",
            6: "",
            7: "",
            "#": 4,
            "Groepsgrootte": 29,
        },
        ("Geel", "Meisje"): {
            1: "Julia (Kab)",
            2: "Noor (Kab)",
            3: "Zoe (Kab)",
            4: "Feline (Vli)",
            5: "Iris (Vli)",
            6: "Nina (Vli)",
            7: "",
            "#": 6,
            "Groepsgrootte": np.nan,
        },
        ("Groen", "Jongen"): {
            1: "Jurre (Kab)",
            2: "SiemX. (Kab)",
            3: "Tijn (Kab)",
            4: "SiemY. (Vli)",
            5: "Stijn (Vli)",
            6: "",
            7: "",
            "#": 5,
            "Groepsgrootte": 29,
        },
        ("Groen", "Meisje"): {
            1: "Lynn (Kab)",
            2: "Amy (Tor)",
            3: "Lotte (Tor)",
            4: "Nora (Tor)",
            5: "Jill (Vli)",
            6: "Sophie (Vli)",
            7: "",
            "#": 6,
            "Groepsgrootte": np.nan,
        },
        ("Oranje", "Jongen"): {
            1: "Jayden (Tor)",
            2: "Max (Tor)",
            3: "Bram (Tov)",
            4: "Cas (Tov)",
            5: "David (Tov)",
            6: "",
            7: "",
            "#": 5,
            "Groepsgrootte": 29,
        },
        ("Oranje", "Meisje"): {
            1: "LivA. (Tor)",
            2: "LivB. (Tor)",
            3: "Vera (Tor)",
            4: "Eline (Tov)",
            5: "Anna (Vli)",
            6: "Emily (Vli)",
            7: "Fenna (Vli)",
            "#": 7,
            "Groepsgrootte": np.nan,
        },
    }
    df_expected_groepsindeling = pd.DataFrame(expected_groepsindeling)
    df_expected_groepsindeling.columns.names = ["Groep", "Jongen/meisje"]
    return df_expected_groepsindeling


def get_expected_klassenoverzicht():
    expected = {
        "Jongen": {
            ("Blauw", "Jaarlaag"): 5,
            ("Blauw", "Totaal"): 14,
            ("Geel", "Jaarlaag"): 4,
            ("Geel", "Totaal"): 15,
            ("Groen", "Jaarlaag"): 5,
            ("Groen", "Totaal"): 13,
            ("Oranje", "Jaarlaag"): 5,
            ("Oranje", "Totaal"): 16,
        },
        "Meisje": {
            ("Blauw", "Jaarlaag"): 5,
            ("Blauw", "Totaal"): 16,
            ("Geel", "Jaarlaag"): 6,
            ("Geel", "Totaal"): 14,
            ("Groen", "Jaarlaag"): 6,
            ("Groen", "Totaal"): 16,
            ("Oranje", "Jaarlaag"): 7,
            ("Oranje", "Totaal"): 13,
        },
        "VerschilJongensMeisjes": {
            ("Blauw", "Jaarlaag"): 0,
            ("Blauw", "Totaal"): 2,
            ("Geel", "Jaarlaag"): 2,
            ("Geel", "Totaal"): 1,
            ("Groen", "Jaarlaag"): 1,
            ("Groen", "Totaal"): 3,
            ("Oranje", "Jaarlaag"): 2,
            ("Oranje", "Totaal"): 3,
        },
        "Groepsgrootte": {
            ("Blauw", "Jaarlaag"): 10,
            ("Blauw", "Totaal"): 30,
            ("Geel", "Jaarlaag"): 10,
            ("Geel", "Totaal"): 29,
            ("Groen", "Jaarlaag"): 11,
            ("Groen", "Totaal"): 29,
            ("Oranje", "Jaarlaag"): 12,
            ("Oranje", "Totaal"): 29,
        },
    }
    return pd.DataFrame(expected)


def get_expected_overgangsmatrix():
    expected = {
        "Blauw": {"Kaboutertuin": 5, "Torteltuin": 2, "Tovertuin": 3, "Vlindertuin": 0},
        "Geel": {"Kaboutertuin": 3, "Torteltuin": 0, "Tovertuin": 2, "Vlindertuin": 5},
        "Groen": {"Kaboutertuin": 4, "Torteltuin": 3, "Tovertuin": 0, "Vlindertuin": 4},
        "Oranje": {
            "Kaboutertuin": 0,
            "Torteltuin": 5,
            "Tovertuin": 4,
            "Vlindertuin": 3,
        },
    }
    df = pd.DataFrame(expected)
    df.index.name = "Stamgroep"
    df.columns.name = "Group"
    return df


def get_expected_leerlingtevredenheid():
    expected = {
        "Tevredenheid": {
            "Adam": 0.9032258064516,
            "Amy": 0.6672997258392,
            "Anna": 0.9921259842519,
            "Anne": 1.0,
            "AnneClaire": 0.8571428571429,
            "Benjamin": 0.7387961250363,
            "Bram": 0.7741935483871,
            "Cas": 0.8571428571429,
            "Daan": 1.0,
            "David": 0.8571428571429,
            "Eline": 0.6610539765808,
            "Emily": 0.9921259842519,
            "Esmee": 0.7852627661454,
            "Feline": 0.7387961250363,
            "Fenna": 0.7846782049872,
            "Iris": 0.5714285714286,
            "Jack": 0.7846782049872,
            "Jayden": 1.0,
            "Jill": 0.6666666666667,
            "Julia": 0.984126984127,
            "Julian": 0.709124996087,
            "Jurre": 0.6666666666667,
            "Lars": 0.6666666666667,
            "LivA.": 0.8947718513662,
            "LivB.": 0.8888888888889,
            "Lois": 1.0,
            "Lotte": 0.7846782049872,
            "Lucas": 0.5714285714286,
            "Lynn": 1.0,
            "Mats": 0.8818897637795,
            "Max": 0.8418251890711,
            "Naomi": 1.0,
            "Nina": 0.8,
            "Noor": 0.8571428571429,
            "Nora": 0.9333333333333,
            "SiemX.": 0.6666666666667,
            "SiemY.": 0.709124996087,
            "Sophie": 0.6666666666667,
            "Stijn": 0.8,
            "Sven": 0.6666666666667,
            "Tijn": 0.6666666666667,
            "Vera": 0.8,
            "Zoe": 0.9795728532373,
        },
        "Aantal gehonoreerde wensen": {
            "Adam": 3.0,
            "Amy": 1.5,
            "Anna": 6.0,
            "Anne": 2.5,
            "AnneClaire": 2.0,
            "Benjamin": 1.5,
            "Bram": 2.0,
            "Cas": 2.0,
            "Daan": 2.0,
            "David": 2.0,
            "Eline": 1.5,
            "Emily": 6.0,
            "Esmee": 1.5,
            "Feline": 1.5,
            "Fenna": 2.0,
            "Iris": 1.0,
            "Jack": 2.0,
            "Jayden": 4.5,
            "Jill": 1.0,
            "Julia": 5.0,
            "Julian": 1.5,
            "Jurre": 1.0,
            "Lars": 1.0,
            "LivA.": 3.0,
            "LivB.": 3.0,
            "Lois": 1.0,
            "Lotte": 2.0,
            "Lucas": 1.0,
            "Lynn": 1.0,
            "Mats": 3.0,
            "Max": 2.5,
            "Naomi": 1.0,
            "Nina": 2.0,
            "Noor": 2.0,
            "Nora": 3.0,
            "SiemX.": 1.0,
            "SiemY.": 1.5,
            "Sophie": 1.0,
            "Stijn": 2.0,
            "Sven": 1.0,
            "Tijn": 1.0,
            "Vera": 2.0,
            "Zoe": 5.0,
        },
        "Aantal wensen": {
            "Adam": 5.0,
            "Amy": 5.0,
            "Anna": 7.0,
            "Anne": 2.5,
            "AnneClaire": 3.0,
            "Benjamin": 3.0,
            "Bram": 5.0,
            "Cas": 3.0,
            "Daan": 2.0,
            "David": 3.0,
            "Eline": 5.5,
            "Emily": 7.0,
            "Esmee": 2.5,
            "Feline": 3.0,
            "Fenna": 4.5,
            "Iris": 3.0,
            "Jack": 4.5,
            "Jayden": 4.5,
            "Jill": 2.0,
            "Julia": 6.0,
            "Julian": 3.5,
            "Jurre": 2.0,
            "Lars": 2.0,
            "LivA.": 5.5,
            "LivB.": 6.0,
            "Lois": 1.0,
            "Lotte": 4.5,
            "Lucas": 3.0,
            "Lynn": 1.0,
            "Mats": 7.0,
            "Max": 5.5,
            "Naomi": 1.0,
            "Nina": 4.0,
            "Noor": 3.0,
            "Nora": 4.0,
            "SiemX.": 2.0,
            "SiemY.": 3.5,
            "Sophie": 2.0,
            "Stijn": 4.0,
            "Sven": 2.0,
            "Tijn": 2.0,
            "Vera": 4.0,
            "Zoe": 6.5,
        },
    }
    df = pd.DataFrame(expected)
    df.index.name = "Leerling"
    return df


def get_expected_vervuldewensen():
    expected = {
        ("MinimaleTevredenheid", np.nan, np.nan): {
            "Daan": np.nan,
            "Jack": np.nan,
            "Anne": np.nan,
            "Bram": np.nan,
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": 0.5,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": np.nan,
            "LivA.": np.nan,
            "LivB.": np.nan,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": 0.5,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": 0.5,
        },
        ("Jongen/meisje", np.nan, np.nan): {
            "Daan": "Jongen",
            "Jack": "Jongen",
            "Anne": "Meisje",
            "Bram": "Jongen",
            "Esmee": "Meisje",
            "Julian": "Jongen",
            "Cas": "Jongen",
            "Eline": "Meisje",
            "David": "Jongen",
            "AnneClaire": "Meisje",
            "Julia": "Meisje",
            "Lucas": "Jongen",
            "Jurre": "Jongen",
            "Naomi": "Meisje",
            "Jayden": "Jongen",
            "Benjamin": "Jongen",
            "Lotte": "Meisje",
            "Amy": "Meisje",
            "Mats": "Jongen",
            "LivA.": "Meisje",
            "LivB.": "Meisje",
            "Max": "Jongen",
            "Nora": "Meisje",
            "Vera": "Meisje",
            "Tijn": "Jongen",
            "Lynn": "Meisje",
            "Zoe": "Meisje",
            "Adam": "Jongen",
            "Lois": "Meisje",
            "SiemX.": "Jongen",
            "Noor": "Meisje",
            "Jill": "Meisje",
            "Nina": "Meisje",
            "Sophie": "Meisje",
            "SiemY.": "Jongen",
            "Feline": "Meisje",
            "Fenna": "Meisje",
            "Sven": "Jongen",
            "Anna": "Meisje",
            "Emily": "Meisje",
            "Stijn": "Jongen",
            "Lars": "Jongen",
            "Iris": "Meisje",
        },
        ("Stamgroep", np.nan, np.nan): {
            "Daan": "Tovertuin",
            "Jack": "Tovertuin",
            "Anne": "Tovertuin",
            "Bram": "Tovertuin",
            "Esmee": "Tovertuin",
            "Julian": "Tovertuin",
            "Cas": "Tovertuin",
            "Eline": "Tovertuin",
            "David": "Tovertuin",
            "AnneClaire": "Kaboutertuin",
            "Julia": "Kaboutertuin",
            "Lucas": "Kaboutertuin",
            "Jurre": "Kaboutertuin",
            "Naomi": "Kaboutertuin",
            "Jayden": "Torteltuin",
            "Benjamin": "Torteltuin",
            "Lotte": "Torteltuin",
            "Amy": "Torteltuin",
            "Mats": "Torteltuin",
            "LivA.": "Torteltuin",
            "LivB.": "Torteltuin",
            "Max": "Torteltuin",
            "Nora": "Torteltuin",
            "Vera": "Torteltuin",
            "Tijn": "Kaboutertuin",
            "Lynn": "Kaboutertuin",
            "Zoe": "Kaboutertuin",
            "Adam": "Kaboutertuin",
            "Lois": "Kaboutertuin",
            "SiemX.": "Kaboutertuin",
            "Noor": "Kaboutertuin",
            "Jill": "Vlindertuin",
            "Nina": "Vlindertuin",
            "Sophie": "Vlindertuin",
            "SiemY.": "Vlindertuin",
            "Feline": "Vlindertuin",
            "Fenna": "Vlindertuin",
            "Sven": "Vlindertuin",
            "Anna": "Vlindertuin",
            "Emily": "Vlindertuin",
            "Stijn": "Vlindertuin",
            "Lars": "Vlindertuin",
            "Iris": "Vlindertuin",
        },
        ("Graag met", 1.0, "Waarde"): {
            "Daan": "Jack",
            "Jack": "Daan",
            "Anne": "Blauw",
            "Bram": "Geel",
            "Esmee": "Blauw",
            "Julian": "Blauw",
            "Cas": "David",
            "Eline": "Geel",
            "David": "Cas",
            "AnneClaire": "Naomi",
            "Julia": "Zoe",
            "Lucas": "David",
            "Jurre": "Tijn",
            "Naomi": "AnneClaire",
            "Jayden": "Vera",
            "Benjamin": "Mats",
            "Lotte": "Groen",
            "Amy": "LivB.",
            "Mats": "Blauw",
            "LivA.": "Vera",
            "LivB.": "Amy",
            "Max": "Geel",
            "Nora": "Lotte",
            "Vera": "Groen",
            "Tijn": "SiemX.",
            "Lynn": "Nora",
            "Zoe": "Julia",
            "Adam": "Blauw",
            "Lois": "AnneClaire",
            "SiemX.": "Tijn",
            "Noor": "Blauw",
            "Jill": "Sophie",
            "Nina": "Sophie",
            "Sophie": "Feline",
            "SiemY.": "Groen",
            "Feline": "Sophie",
            "Fenna": "Eline",
            "Sven": "SiemY.",
            "Anna": "Emily",
            "Emily": "Anna",
            "Stijn": "Sven",
            "Lars": "SiemY.",
            "Iris": "Feline",
        },
        ("Graag met", 1.0, "Gewicht"): {
            "Daan": 2.0,
            "Jack": 2.0,
            "Anne": 1.5,
            "Bram": 1.0,
            "Esmee": 1.5,
            "Julian": 1.5,
            "Cas": 2.0,
            "Eline": 2.0,
            "David": 2.0,
            "AnneClaire": np.nan,
            "Julia": 5.0,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": 1.0,
            "Benjamin": 1.5,
            "Lotte": 2.0,
            "Amy": 1.5,
            "Mats": 1.5,
            "LivA.": 1.5,
            "LivB.": 1.5,
            "Max": 1.5,
            "Nora": 1.0,
            "Vera": 2.0,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": 5.0,
            "Adam": 3.0,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": 1.5,
            "Feline": 1.5,
            "Fenna": 2.0,
            "Sven": np.nan,
            "Anna": 5.0,
            "Emily": 5.0,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Graag met", 2.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": "David",
            "Anne": "Esmee",
            "Bram": "Eline",
            "Esmee": "Bram",
            "Julian": "Bram",
            "Cas": "Jack",
            "Eline": "Anne",
            "David": "Jack",
            "AnneClaire": "Lynn",
            "Julia": "Blauw",
            "Lucas": "Geel",
            "Jurre": "Jack",
            "Naomi": np.nan,
            "Jayden": "LivB.",
            "Benjamin": "Max",
            "Lotte": "LivA.",
            "Amy": "Lotte",
            "Mats": "Vera",
            "LivA.": "Lotte",
            "LivB.": "LivA.",
            "Max": "Mats",
            "Nora": "LivA.",
            "Vera": "LivA.",
            "Tijn": "Julia",
            "Lynn": np.nan,
            "Zoe": "SiemX.",
            "Adam": "SiemX.",
            "Lois": np.nan,
            "SiemX.": "Zoe",
            "Noor": "Zoe",
            "Jill": "Feline",
            "Nina": "Feline",
            "Sophie": "Jill",
            "SiemY.": "Sven",
            "Feline": "Nina",
            "Fenna": "Jill",
            "Sven": "Lars",
            "Anna": "LivB.",
            "Emily": "LivB.",
            "Stijn": "SiemY.",
            "Lars": "Sven",
            "Iris": "Anna",
        },
        ("Graag met", 2.0, "Gewicht"): {
            "Daan": np.nan,
            "Jack": 1.0,
            "Anne": 1.0,
            "Bram": 1.0,
            "Esmee": 1.0,
            "Julian": 1.0,
            "Cas": 1.0,
            "Eline": 1.0,
            "David": 1.0,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": 1.5,
            "Benjamin": 1.5,
            "Lotte": 1.5,
            "Amy": 1.5,
            "Mats": 1.5,
            "LivA.": 1.5,
            "LivB.": 1.5,
            "Max": 1.5,
            "Nora": 1.0,
            "Vera": 1.0,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": 1.0,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Graag met", 3.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": "Bram",
            "Anne": np.nan,
            "Bram": "Jack",
            "Esmee": np.nan,
            "Julian": "Cas",
            "Cas": np.nan,
            "Eline": "Fenna",
            "David": np.nan,
            "AnneClaire": "Blauw",
            "Julia": np.nan,
            "Lucas": "Blauw",
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": "Oranje",
            "Benjamin": np.nan,
            "Lotte": "Vera",
            "Amy": "Mats",
            "Mats": "Amy",
            "LivA.": "LivB.",
            "LivB.": "Vera",
            "Max": "LivB.",
            "Nora": "Groen",
            "Vera": "LivB.",
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": "Tijn",
            "Adam": "Jurre",
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": "Julia",
            "Jill": np.nan,
            "Nina": "Groen",
            "Sophie": np.nan,
            "SiemY.": "Lars",
            "Feline": "Iris",
            "Fenna": "Sophie",
            "Sven": np.nan,
            "Anna": "Amy",
            "Emily": "Amy",
            "Stijn": "Lars",
            "Lars": np.nan,
            "Iris": "Jill",
        },
        ("Graag met", 3.0, "Gewicht"): {
            "Daan": np.nan,
            "Jack": 1.0,
            "Anne": np.nan,
            "Bram": 1.0,
            "Esmee": np.nan,
            "Julian": 1.0,
            "Cas": np.nan,
            "Eline": 1.5,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": 1.0,
            "Amy": 1.0,
            "Mats": 1.0,
            "LivA.": 1.5,
            "LivB.": 1.5,
            "Max": 1.5,
            "Nora": 2.0,
            "Vera": 1.0,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": 0.5,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": 0.5,
            "Fenna": np.nan,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Graag met", 4.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": "Groen",
            "Anne": np.nan,
            "Bram": "David",
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": "Sophie",
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": "Max",
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": "Geel",
            "Mats": "Benjamin",
            "LivA.": "Nora",
            "LivB.": "Geel",
            "Max": "Jayden",
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": "Geel",
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": "Geel",
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": "Groen",
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Graag met", 4.0, "Gewicht"): {
            "Daan": np.nan,
            "Jack": 0.5,
            "Anne": np.nan,
            "Bram": 1.0,
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": 1.0,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": 1.0,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": 1.5,
            "LivA.": 1.0,
            "LivB.": 1.5,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": 0.5,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Graag met", 5.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": np.nan,
            "Anne": np.nan,
            "Bram": "Anne",
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": "Geel",
            "LivA.": np.nan,
            "LivB.": np.nan,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Graag met", 5.0, "Gewicht"): {
            "Daan": np.nan,
            "Jack": np.nan,
            "Anne": np.nan,
            "Bram": 1.0,
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": 1.5,
            "LivA.": np.nan,
            "LivB.": np.nan,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Liever niet met", 1.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": np.nan,
            "Anne": "Nora",
            "Bram": "Daan",
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": "Lucas",
            "Naomi": "Oranje",
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": np.nan,
            "LivA.": np.nan,
            "LivB.": np.nan,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": "AnneClaire",
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": "Adam",
            "Noor": "Oranje",
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": "Blauw",
            "Anna": "Geel",
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": "Stijn",
            "Iris": np.nan,
        },
        ("Liever niet met", 1.0, "Gewicht"): {
            "Daan": np.nan,
            "Jack": np.nan,
            "Anne": 1.5,
            "Bram": 1.0,
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": np.nan,
            "LivA.": np.nan,
            "LivB.": np.nan,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": 2.0,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": 0.5,
            "Iris": np.nan,
        },
        ("Niet in", 1.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": "Blauw",
            "Anne": np.nan,
            "Bram": np.nan,
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": "Geel",
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": "Groen",
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": "Oranje",
            "Mats": "Groen",
            "LivA.": np.nan,
            "LivB.": "Blauw",
            "Max": "Groen",
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": "Geel",
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": "Oranje",
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": "Oranje",
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": "Groen",
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
        ("Niet in", 2.0, "Waarde"): {
            "Daan": np.nan,
            "Jack": np.nan,
            "Anne": np.nan,
            "Bram": np.nan,
            "Esmee": np.nan,
            "Julian": np.nan,
            "Cas": np.nan,
            "Eline": np.nan,
            "David": np.nan,
            "AnneClaire": np.nan,
            "Julia": np.nan,
            "Lucas": np.nan,
            "Jurre": np.nan,
            "Naomi": np.nan,
            "Jayden": np.nan,
            "Benjamin": np.nan,
            "Lotte": np.nan,
            "Amy": np.nan,
            "Mats": np.nan,
            "LivA.": np.nan,
            "LivB.": np.nan,
            "Max": np.nan,
            "Nora": np.nan,
            "Vera": np.nan,
            "Tijn": np.nan,
            "Lynn": np.nan,
            "Zoe": np.nan,
            "Adam": np.nan,
            "Lois": np.nan,
            "SiemX.": np.nan,
            "Noor": np.nan,
            "Jill": np.nan,
            "Nina": np.nan,
            "Sophie": np.nan,
            "SiemY.": np.nan,
            "Feline": np.nan,
            "Fenna": np.nan,
            "Sven": np.nan,
            "Anna": np.nan,
            "Emily": np.nan,
            "Stijn": np.nan,
            "Lars": np.nan,
            "Iris": np.nan,
        },
    }
    df = pd.DataFrame(expected)
    df.index.name = "Leerling"
    df.columns.names = ["TypeWens", "Nr", "TypeWaarde"]
    return df
