"""Create the homepage gallery from the real ALI Express application.

The integration workbook is the source of truth for these images. This script creates
an isolated temporary application, stores the workbook through the same data contracts
as the Excel upload route, runs the real solver, and takes Playwright screenshots of the
real preferences form, result page, satisfaction analysis, and sociogram.

Run from the repository root with::

    UV_CACHE_DIR=/tmp/aliexpress-uv-cache uv run python scripts/generate_home_gallery_assets.py

The generated files are written to ``static/images`` because that is where the homepage
template reads them from. No HTML is generated by this script.

The start control uses the explicit ``data-testid`` also exercised by the browser smoke
test in ``tests/browser/test_distribution_browser.py``. Run that test after changing the
processing page or this script so a changed button label cannot silently break generation::

    UV_CACHE_DIR=/tmp/aliexpress-uv-cache uv run pytest \
        tests/browser/test_distribution_browser.py -q --no-cov \
        -k processing_to_result_to_download
"""

from __future__ import annotations

import json
import shutil
import tempfile
import threading
from pathlib import Path

from playwright.sync_api import Page, sync_playwright
from werkzeug.security import generate_password_hash
from werkzeug.serving import make_server

from aliexpress import create_app
from aliexpress.data import datareader
from aliexpress.web.extensions import db
from aliexpress.web.models import Process, School
from aliexpress.web.process_files import (
    save_candidates,
    save_input_method,
    save_not_together,
    save_preferences_excel,
    save_roster,
    save_voorkeuren,
)

ROOT = Path(__file__).resolve().parents[1]
PREFERENCES_SOURCE = ROOT / "tests" / "integration" / "voorkeuren.xlsx"
GROUPS_SOURCE = ROOT / "tests" / "integration" / "groepen.xlsx"
NOT_TOGETHER_SOURCE = ROOT / "tests" / "integration" / "not_together_full.json"
OUTPUT = ROOT / "static" / "images"

SCHOOL_CODE = "homepage-gallery-school"
PROCESS_NAME = "homepage-gallery"
PASSWORD = "homepage-gallery-pass"
START_DISTRIBUTION_TEST_ID = "start-distribution"
GROUP_CARDS_TEST_ID = "group-cards"
STUDENT_SATISFACTION_TEST_ID = "student-satisfaction"


def _participants(processor: datareader.VoorkeurenProcessor) -> list[dict]:
    """Convert the workbook's real students to the roster contract.

    The workbook intentionally contains first names only. An empty surname preserves
    those display names while still exercising the same roster/preferences-form route
    used by a normal process.
    """
    meta = processor.get_students_meta_info()
    participants = []
    for key, info in meta.items():
        participants.append(
            {
                "key": key,
                "roepnaam": processor.student_display[key],
                "achternaam": "",
                "groepsnaam": processor.stamgroep_display[info["Stamgroep"]],
                "geslacht": info["Jongen/meisje"],
                "jaargroep": None,
            }
        )
    return participants


def _prepare_process(app, storage_dir: Path) -> datareader.VoorkeurenProcessor:
    """Load the real workbook and create the minimum complete application process."""
    raw_preferences = PREFERENCES_SOURCE.read_bytes()
    processor = datareader.VoorkeurenProcessor(PREFERENCES_SOURCE)
    target_groups = datareader.read_groups_excel(GROUPS_SOURCE)
    processor.process(all_to_groups=list(target_groups.counts))

    process_dir = storage_dir / SCHOOL_CODE / PROCESS_NAME
    process_dir.mkdir(parents=True)
    shutil.copyfile(GROUPS_SOURCE, process_dir / "groups.xlsx")

    participants = _participants(processor)
    candidates = [dict(student) for student in participants]
    save_candidates(
        SCHOOL_CODE,
        PROCESS_NAME,
        {
            "candidates": candidates,
            "groups_from": sorted({student["groepsnaam"] for student in participants})
            + ["Anders"],
            "groups_to": target_groups.counts,
            "jaargroepen": [],
        },
    )
    save_roster(SCHOOL_CODE, PROCESS_NAME, {"participants": participants})
    save_preferences_excel(SCHOOL_CODE, PROCESS_NAME, raw_preferences)
    save_voorkeuren(
        SCHOOL_CODE, PROCESS_NAME, processor.to_preference_data(), source="excel"
    )
    save_input_method(SCHOOL_CODE, PROCESS_NAME, "excel")

    if NOT_TOGETHER_SOURCE.exists():
        save_not_together(
            SCHOOL_CODE,
            PROCESS_NAME,
            json.loads(NOT_TOGETHER_SOURCE.read_text(encoding="utf-8")),
        )
    else:
        save_not_together(SCHOOL_CODE, PROCESS_NAME, [])

    with app.app_context():
        db.session.add(Process(school_id=SCHOOL_CODE, name=PROCESS_NAME))
        db.session.commit()
    return processor


def _workbook_example(
    processor: datareader.VoorkeurenProcessor,
) -> tuple[str, str]:
    """Return one real workbook student and their first positive preference."""
    positive = processor.df[
        processor.df.index.get_level_values("TypeWens") == "Graag met"
    ]
    if positive.empty:
        raise ValueError("The integration workbook has no positive preference")
    owner_key = positive.index[0][0]
    target_key = positive.iloc[0]["Waarde"]
    target_display = processor.student_display.get(
        target_key,
        processor.stamgroep_display.get(target_key, target_key),
    )
    return owner_key, target_display


def _login(page: Page, base_url: str) -> None:
    page.goto(f"{base_url}/login")
    page.fill("#schoolcode", SCHOOL_CODE)
    page.fill("#wachtwoord", PASSWORD)
    page.click('button[type="submit"]')
    page.wait_for_url(f"{base_url}/processes")


def _capture_preferences(
    page: Page, base_url: str, owner_key: str, target_display: str, output: Path
) -> None:
    """Capture the real form with a preference from the workbook filled in."""
    page.goto(f"{base_url}/preferences_form")
    row = page.locator(f'.candidate-row[data-key="{owner_key}"]')
    row.click()
    preference_input = page.locator(f"#combo-graag_met-{owner_key}")
    preference_input.fill(target_display)
    preference_input.press("Enter")
    page.screenshot(path=str(output), type="png")


def _capture_group_cards(page: Page, base_url: str, output: Path) -> None:
    """Capture only the real solved grouping's group cards."""
    page.goto(f"{base_url}/result")
    page.get_by_test_id(GROUP_CARDS_TEST_ID).screenshot(path=str(output), type="png")


def _capture_satisfaction(page: Page, base_url: str, output: Path) -> None:
    """Capture the result's satisfaction analysis with varied, mostly positive scores."""
    page.goto(f"{base_url}/result")
    analysis = page.get_by_test_id(STUDENT_SATISFACTION_TEST_ID)
    analysis.locator("summary").click()
    analysis.locator(".result-student-list").wait_for(state="visible")

    scores = page.locator(
        f'[data-testid="{STUDENT_SATISFACTION_TEST_ID}"] .gi-satdot'
    ).evaluate_all(
        "elements => elements.map(element => element.getAttribute('aria-label'))"
    )
    numeric_scores = [
        int(score.removeprefix("Tevredenheid ").removesuffix("%"))
        for score in scores
        if score and score.startswith("Tevredenheid ")
    ]
    if len(set(numeric_scores)) < 3:
        raise RuntimeError("The homepage satisfaction example needs varied scores")
    if sum(score > 0 for score in numeric_scores) <= len(numeric_scores) / 2:
        raise RuntimeError("The homepage satisfaction example is not mostly positive")

    analysis.scroll_into_view_if_needed()
    box = analysis.bounding_box()
    if box is None:
        raise RuntimeError("Could not locate the satisfaction analysis")
    page.screenshot(
        path=str(output),
        type="png",
        clip={
            "x": box["x"],
            "y": box["y"],
            "width": box["width"],
            "height": min(box["height"], 800),
        },
    )


def _capture_sociogram(page: Page, base_url: str, output: Path) -> None:
    """Capture the real Cytoscape sociogram after its layout has settled."""
    page.goto(f"{base_url}/sociogram")
    page.wait_for_function("() => window.sociogramReady === true", timeout=120_000)
    page.locator("#sociogram").scroll_into_view_if_needed()
    page.screenshot(path=str(output), type="png")


def main() -> None:
    """Build all four homepage gallery images from the real application screens."""
    for source in (PREFERENCES_SOURCE, GROUPS_SOURCE):
        if not source.exists():
            raise FileNotFoundError(f"Expected integration source is missing: {source}")

    OUTPUT.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="aliexpress-home-gallery-") as temp_dir:
        storage_dir = Path(temp_dir)
        app = create_app(
            {
                "TESTING": True,
                "SECRET_KEY": "homepage-gallery-secret",
                "ADMIN_PASSWORD": "homepage-gallery-admin-password",
                "SQLALCHEMY_DATABASE_URI": "sqlite://",
                "STORAGE_DIR": str(storage_dir),
            }
        )
        with app.app_context():
            db.session.add(
                School(
                    schoolcode=SCHOOL_CODE,
                    naam="Homepage galerij",
                    password_hash=generate_password_hash(
                        PASSWORD, method="pbkdf2:sha256:1"
                    ),
                )
            )
            db.session.commit()
        with app.app_context():
            processor = _prepare_process(app, storage_dir)
            owner_key, target_display = _workbook_example(processor)

        server = make_server("127.0.0.1", 0, app, threaded=True)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        try:
            base_url = f"http://127.0.0.1:{server.server_port}"
            with sync_playwright() as playwright:
                browser = playwright.chromium.launch(headless=True)
                page = browser.new_page(
                    viewport={"width": 1440, "height": 900}, device_scale_factor=1
                )
                _login(page, base_url)
                page.goto(f"{base_url}/processes/select/{PROCESS_NAME}")
                _capture_preferences(
                    page,
                    base_url,
                    owner_key,
                    target_display,
                    OUTPUT / "home-gallery-voorkeuren.png",
                )

                page.goto(f"{base_url}/processing")
                page.get_by_test_id(START_DISTRIBUTION_TEST_ID).click()
                page.wait_for_url("**/result", timeout=300_000)
                _capture_group_cards(
                    page,
                    base_url,
                    OUTPUT / "home-gallery-resultaat.png",
                )
                _capture_satisfaction(
                    page, base_url, OUTPUT / "home-gallery-tevredenheid.png"
                )
                _capture_sociogram(
                    page, base_url, OUTPUT / "home-gallery-sociogram.png"
                )
                browser.close()
        finally:
            server.shutdown()
            thread.join()


if __name__ == "__main__":
    main()
